[tool.black]
line-length = 120

[tool.pytest.ini_options]
minversion = "6.0"
addopts = '''
  -v
  -rs
  --strict-config
  --strict-markers
  --showlocals
  --black
  --flake8
  --isort
  --mypy

  --junitxml=junit/test-results.xml

  --cov=.
  --cov-branch
  --cov-report xml:cov.xml
  --cov-report html:htmlcov
  --cov-report term
  --cov-fail-under=80
'''

[tool.coverage.run]
branch=true
omit = [
  '**/test_*.py',
  '**/__init__.py',
  '.venv/**/*.py',
  'test/',
]

[tool.flake8]
max-line-length = 120
max-complexity = 10

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
import_heading_stdlib='Standard Library'
import_heading_thirdparty='Third Party Libraries'
import_heading_firstparty='Our Libraries'

[tool.mypy]
mypy_path = 'mydash'
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true
